// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf0uhfHlM7uk1u-ByDECH29j356v5Bhh0',
    appId: '1:882491380012:web:3ed4fc210a413a19341c89',
    messagingSenderId: '882491380012',
    projectId: 'met-school-codemates',
    authDomain: 'met-school-codemates.firebaseapp.com',
    storageBucket: 'met-school-codemates.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9N-Hi7uMH39J7JSX9XrGUycjmcrTWl7s',
    appId: '1:882491380012:android:b23d08458aaacac9341c89',
    messagingSenderId: '882491380012',
    projectId: 'met-school-codemates',
    storageBucket: 'met-school-codemates.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0NSouV6-Q7vJsmI-C7M6Mbzu6yd3xP6c',
    appId: '1:882491380012:ios:39ea980ad5447e23341c89',
    messagingSenderId: '882491380012',
    projectId: 'met-school-codemates',
    storageBucket: 'met-school-codemates.firebasestorage.app',
    iosBundleId: 'com.codemates.metSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0NSouV6-Q7vJsmI-C7M6Mbzu6yd3xP6c',
    appId: '1:882491380012:ios:39ea980ad5447e23341c89',
    messagingSenderId: '882491380012',
    projectId: 'met-school-codemates',
    storageBucket: 'met-school-codemates.firebasestorage.app',
    iosBundleId: 'com.codemates.metSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf0uhfHlM7uk1u-ByDECH29j356v5Bhh0',
    appId: '1:882491380012:web:58f2f6e81eaac203341c89',
    messagingSenderId: '882491380012',
    projectId: 'met-school-codemates',
    authDomain: 'met-school-codemates.firebaseapp.com',
    storageBucket: 'met-school-codemates.firebasestorage.app',
  );
}
